module "web_load_balancer" {
  source = "./modules/loadbalancer"

  resource_group_name            = "test-resource-group-anirudh"
  location                       = "northcentralus"
  BackEndAddressPool_name        = "test"
  application_name               = "sampleapp"
  backend_port                   = 80
  backend_port_2                 = 8080
  disable_outbound_snat          = false
  disable_outbound_snat_2        = false
  enable_floating_ip             = true
  enable_floating_ip_2           = true
  probe_name                     = "testprobe"
  frontend_port                  = 80
  frontend_port_2                = 8080
  enable_tcp_reset               = true
  enable_tcp_reset_2             = true
  number_of_probes               = 5
  port                           = 202
  load_distribution              = "Default"
  load_distribution_2            = "Default"
  lb_rule_name                   = "rule1"
  lb_rule_name_2                 = "rule2"
  lb_sku                         = "Basic"
  frontend_ip_configuration_name = "fip"
  public_ip_allocation_method    = "Static"
  public_ip_sku                  = "Standard"
  protocol                       = "Tcp"
  protocol_2                     = "Tcp"
  interval_in_seconds            = 5
  idle_timeout_in_minutes        = 4
  idle_timeout_in_minutes_2      = 4
  owner                          = "Anirudh"
  public_ip_address_id           = "test"
}